removing circle and ensuring we redirect to active libraries
RedisTimeSeries/JRedisTimeSeries pull request #85
Opened 2022-12-08 08:50 UTC by chayim

2022-12-08 09:46 UTC, sazzad16 requested changes
Where is _"ensuring we redirect to active libraries"_?

2022-12-30 21:13 UTC, gkorland approved these changes

2022-12-30 21:15 UTC, gkorland commented
I stopped the CI in CircleCI

2022-12-31 10:05 UTC, sazzad16 approved these changes

2022-12-31 10:05 UTC, merged